name: teamapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  firebase_storage:
  provider: ^4.0.4
  flutter_svg: ^0.17.3+1
  flutter_spinkit: ^4.1.2+1
  flutter_typeahead: ^1.8.0
  image_picker: ^0.6.0+9
  image_cropper: ^1.2.1
  photo_view: ^0.9.2
  path_provider: ^1.6.7
  date_format:
  gender_selection: ^1.0.0
  timeago: ^2.0.26
  enum_to_string: ^1.0.9


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/tests/1.jpg
    - assets/tests/2.jpg
    - assets/tests/3.png
    - assets/tests/4.jpg
    - assets/icons/options-halved.svg
    - assets/icons/icons8-gender-100.png
    - assets/icons/icons8-age-100.png
    - assets/logos/facebook.jpg
    - assets/logos/facebook.svg
    - assets/logos/google.jpg
    - assets/logos/google.svg
    - assets/logos/teamapp_1.png
    - assets/logos/teamapp.png

    - assets/images/background_1.png
    - assets/images/background_2.png
    - assets/images/background_3.png
    - assets/images/background_4.png
    - assets/images/default_profile_image.png
    - assets/images/team.jpg
    - assets/images/touch.svg
    - assets/images/three_friends_play.png
    - assets/images/number_one.jpg


  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Open_Sans/OpenSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Open_Sans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/Open_Sans/OpenSans-Light.ttf
          weight: 300

          style: italic
        - asset: assets/fonts/Open_Sans/OpenSans-ExtraBoldItalic.ttf
          weight: 700
        - asset: assets/fonts/Open_Sans/OpenSans-BoldItalic.ttf
          weight: 600
        - asset: assets/fonts/Open_Sans/OpenSans-SemiBoldItalic.ttf
          weight: 500
        - asset: assets/fonts/Open_Sans/OpenSans-Italic.ttf
          weight: 400
        - asset: assets/fonts/Open_Sans/OpenSans-LightItalic.ttf
          weight: 300


    - family: Heebo
      fonts:
        - asset: assets/fonts/Heebo/Heebo-Black.ttf
        - asset: assets/fonts/Heebo/Heebo-Bold.ttf
        - asset: assets/fonts/Heebo/Heebo-ExtraBold.ttf
        - asset: assets/fonts/Heebo/Heebo-Light.ttf
        - asset: assets/fonts/Heebo/Heebo-Medium.ttf
        - asset: assets/fonts/Heebo/Heebo-Regular.ttf
        - asset: assets/fonts/Heebo/Heebo-Thin.ttf

    - family: Signatra
      fonts:
        - asset: assets/fonts/signatra/Signatra.ttf