import 'package:flutter/cupertino.dart';

class Team {
  // generated by firestore saving process
  String tid;
  String imageUrl;
  String imageRemotePath;
  String ulid; //user list id

  // given by the user
  String name;
  String description;
  bool isPrivate;
  String ownerUid;

  Team.fromDatabase({
    @required this.tid,
    @required this.imageUrl,
    @required this.imageRemotePath,
    @required this.ulid,
    @required this.name,
    @required this.description,
    @required this.isPrivate,
    @required this.ownerUid,
  });

  Team.fromWithinApp({
    @required this.name,
    @required this.description,
    @required this.isPrivate,
    @required this.ownerUid,
  });

  void setUserListID(String ulid) {
    this.ulid = ulid;
  }
}
