import 'package:flutter/cupertino.dart';
import 'package:teamapp/models/storageImage.dart';

enum TeamField { TID, IMAGE, CHAT_ID, NAME, DESCRIPTION, IS_PUBLIC, OWNER_UID }

class Team {
  // generated by firestore saving process
  String tid;
  StorageImage remoteStorageImage;
  String chatId;

  // given by the user
  String name;
  String description;
  bool isPublic;
  String ownerUid;

  Team.fromDatabase(
      {@required this.tid,
      @required this.remoteStorageImage,
      @required this.name,
      @required this.description,
      @required this.isPublic,
      @required this.ownerUid,
      this.chatId});

  Team.fromWithinApp({
    @required this.name,
    @required this.description,
    @required this.isPublic,
    @required this.ownerUid,
  });

  dynamic propAccess(TeamField field, {dynamic newValue}) => <TeamField, dynamic>{
        TeamField.NAME: () => newValue == null ? this.name : this.name = newValue,
        TeamField.DESCRIPTION: () => newValue == null ? this.description : this.description = newValue,
        TeamField.IS_PUBLIC: () => newValue == null ? this.isPublic : this.isPublic = newValue,
        TeamField.OWNER_UID: () => newValue == null ? this.ownerUid : this.ownerUid = newValue,
        TeamField.IMAGE: () => print('\n\nteam image should be updated using team data manager update image!\n\n'),
      }[field]();
}
